### ISSUE TITLE
how to upload new posts whenever i go to domain/ ghost it's givinf 404 error

### ISSUE THREAD

**Issue by anshulpatyal** [styxlab/next-cms-ghost#102]

**Comment by styxlab** [comment]
Welcome @anshulpatyal! Please provide a clear description of the exact steps you are doing. Links to your GItHub clone and domain/sites are also helpful information.

**Comment by anshulpatyal** [comment]
everything works fine until `SITE_URL` but I don't understand (as a beginner) how to create `.env.local`. in project root. please tell me how to do it in visual studio

**Comment by styxlab** [comment]
It is described here: https://github.com/styxlab/next-cms-ghost#building-locally. It is a simple text file that you need to populate with the URL/KEY that you crate in your Ghost Admin interface under integrations.

**Comment by styxlab** [comment]
Close as answered.
