### ISSUE TITLE
Feature: Support building on native Windows

### ISSUE THREAD

**Issue by akshatmittal** [styxlab/next-cms-ghost#11]
This will fail to run on Windows because it uses `path.normalize` for URL pathnames. 

The behavior is very different on Windows and *nix systems and is only recommended for literal file paths and not URL parsing. https://nodejs.org/api/path.html#path_path_normalize_path

Alternative: `URL` class in JS.

**Comment by styxlab** [comment]
Currently this repository only supports *nix and the Windows Subsystem for Linux (WSL), but not native Windows. However, I am open to make it work for native Windows. Please read the previous discussions on #4 and #7.

**Comment by akshatmittal** [comment]
Thanks for pointing me to those discussions, I didn't see them before. At the moment, path normalize is the only thing I see to support Windows. I will have a look at other parts sometime to see if there's anything else that might need changes.

I might PR this change anyway with a solution that works for both *nix and Windows, and not a Windows specific change.

**Comment by styxlab** [comment]
I removed the `path.normalize` dependency, so this does not inhibit native Windows builds anymore. I am closing this issue, but feel free to open a new one, if this does not fully solve the original issue.
