### ISSUE TITLE
Build failed after package update: Type error: Property 'imageDimensions' does not exist on type 'Node<Data>'.

### ISSUE THREAD

**Issue by Buda9** [styxlab/next-cms-ghost#110]
Hi there. It's probably just me but after I updated packages with yarn, I tried deploying it and got this issue below. Do you have any idea how can I solve this issue?

7:35:53 PM: ./components/NextImage.tsx:13:32
7:35:53 PM: Type error: Property 'imageDimensions' does not exist on type 'Node<Data>'.
7:35:53 PM:   11 |   const { node } = props
7:35:53 PM:   12 |   if (!node) return null
7:35:53 PM: > 13 |   const imageDimensions = node.imageDimensions as Dimensions
7:35:53 PM:      |                                ^
7:35:53 PM:   14 |   const { src, className: classArray } = node.properties as PropertyProps
7:35:53 PM:   15 |   const className = classArray?.join(' ')
7:35:53 PM:   16 | 

https://postimg.cc/gallery/q0Dmyj9

**Comment by styxlab** [comment]
Should be fixed with PR #111.

**Comment by Buda9** [comment]
This was super fast. Thank you very much, love the fix! I can confirm it's working fine now
