### ISSUE TITLE
Feature: Sidebar with Author and All Tags Sections

### ISSUE THREAD

**Issue by rbraddev** [styxlab/next-cms-ghost#114]
Implement a sidebar with an author and all tags sections which are present across the whole site.

**Comment by styxlab** [comment]
Hey Ryan!

thanks for your suggestion. The idea of this repo is to replicate the original Ghost Casper theme. I made only a few exceptions to this rule (e.g. the dark mode button, Table Of Contents option, etc.) all of which have one thing in common: they don't change the overall Ghost Capser style and can be viewed as minor, yet helpful additions to the original.

An additional sidebar goes beyond of what I consider a minor theme enhancement, so it is not in scope of this project. That said, I have seen a number of forks of this repo where people included a sidebar with social links, so you can use this project as a starting point for your own customizations.

**Comment by rbraddev** [comment]
Ok, thank you
