### ISSUE TITLE
Ghost>Settings>Publication Language change is not handled in app

### ISSUE THREAD

**Issue by any-me** [styxlab/next-cms-ghost#120]
GhostSettings in ghost.ts ignore passed locale prams

_While utils/use-lang.ts is handling 'en' as default language, change in code to another locale, break the styling._

**Comment by styxlab** [comment]
Welcome @any-me! Thanks for reporting an issue. A different language should be set in the Ghost Admin interface and not by manipulating code. This, of course, only works for languages that are currently available in `utils/lang.ts`, which are: en (default), de, es, ru. New languages must be added to that file first. What languages are you interested in?

**Comment by any-me** [comment]
Great job!
Language change at ghost admin is fully supported by the client.

Style issue is due to font rendering in firefox (on linux) . Can be noticed in the header by switching to 'ru' only, 'es', 'de' & 'en' works correctly.
No problems at chromium based browsers.

I've noticed that 'wide' images are not rendered correctly on small screens ('regular' and 'full' are OK).
Please take a look at screen capture.
Shall i open a new issue?

![wide_img_bad_render](https://user-images.githubusercontent.com/3739505/131235656-7bddc707-87ba-484d-9315-c6c8c989aab3.png)

**Comment by styxlab** [comment]
@any-me : Thanks a lot for reporting these issues. Could you please open 2 new issues and take them out from this one?

1. Style issue with language 'ru' (please provide a screenshot in addition to the info you alreaday provided)
2. Wide images are not correctly displayed on small screens

It's important to separate concerns, I will close this issue after you crated the two new ones.
