### ISSUE TITLE
Help With Deploying

### ISSUE THREAD

**Issue by JaiRelan** [styxlab/next-cms-ghost#122]
Hi everyone,
Slightly new to JS here and needed some help with deploying... 

I clicked on the Deploy To Vercel Button and set went ahead and deployed it on vercel ([https://next-cms-ghost-cskb.vercel.app/](https://next-cms-ghost-cskb.vercel.app/)) - the only problem is that when I try to append `/ghost` at the end of the URL, I get a 404 error.

Thanks a ton in advanced!

**Comment by styxlab** [comment]
Welcome Jai!
This project is only the front-end. You need to run a headless Ghost backend somewhere else. That’s where you’ll find the ‘/ghost’ endpoint.

Von meinem iPhone gesendet

**Comment by styxlab** [comment]
Closed as answered. Please open a [new discussion](https://github.com/styxlab/next-cms-ghost/discussions), if you need further help on this topic.

**Comment by JaiRelan** [comment]
@styxlab - ah, got it. Any guides to a headless ghost you would recommend?

**Comment by styxlab** [comment]
Here is my own guide on [deploying a headless Ghost](https://www.jamify.org/2020/04/07/ghost-cms-on-hetzner-cloud/) instance. The guide focuses on a lesser known provider, but the same steps should work with other cloud providers such as DigitalOcean.

I am not sure if you have already seen it, but I am currently growing my own [Blogging SaaS platform](https://www.blogody.com) where I incorporated all the lessons learned from headless Ghost and other tools. The platform is still in alpha, but already quite powerful and much easier to get started with.

**Comment by JaiRelan** [comment]
Ah @styxlab... Anyway I can talk to you privately about Blogody?

**Comment by styxlab** [comment]
Yes, you can DM me on [twitter](https://www.twitter.com/jamifyjs).

**Comment by JaiRelan** [comment]
Followed you... You probably need to follow me back for me to be able to
message you
