### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by seoxyz** [styxlab/next-cms-ghost#123]
![Screenshot_20210914-170629](https://user-images.githubusercontent.com/54107458/133240242-d5cd4660-1463-4025-9f83-2407042ef7fe.png)

**Comment by styxlab** [comment]
should be fixed with latest commit.

**Comment by seoxyz** [comment]
Thanks bro. 🙏

**Comment by seoxyz** [comment]
Sorry bro, why after updating "/index" appears in Canonical Url? (Index Pages)

**Comment by styxlab** [comment]
Not sure how you get that, I don't see it at https://next.jamify.org/. Please open a new issue, link to a repo and site so I can analyze it.

**Comment by seoxyz** [comment]
@styxlab view-source:https://next.jamify.org/
<link rel="canonical" href="https://next.jamify.org/index"/>
