### ISSUE TITLE
SITE_URL does not work with subdirectories

### ISSUE THREAD

**Issue by timuster** [styxlab/next-cms-ghost#127]
Adding the `SITE_URL` environment variable correctly adds the canonical URL value to every generated page. However, it completely disregards a subdirectory. 

This is a major issue if you want to host your blog on a subdirectory (like /blog). 

For example, if I set my SITE_URL to `https://example.com/blog`, the canonical URLs are written as `https://example.com/*` rather than `https://example.com/blog/*`.

The problem occurs even if you set the `basePath` option to `/blog`.

The root issue is how the `canonical` const is initialized in `seo.tsx`. While `url.resolve()` rewrites the subsdirectory in `siteURL`, `router.asPath` ignores the `basePath`. 

**One simple fix is to change the line (in `seo.tsx`)** to the following and then require `basePath` to be set if folks want to use a subdirectory in `SITE_URL`.
```
const canonical = url.resolve(siteUrl, `${router.basePath}${router.asPath}`);
```

**Comment by styxlab** [comment]
@timuster: The correct way to host your blog on a subdirectory is to use a `basePath` option in `next.config.js` and leave `SITE_URL` as is. It might well be that `${router.basePath}` is missing in a couple of places, so please fell free to open a PR.

**Comment by timuster** [comment]
@styxlab The problem is that the canonical URL ignores the `basePath` completely. The fix I recommended for `seo.tsx` above takes care of all scenarios. I can't open a PR because of contractual reasons, but please feel free to use it.

**Comment by styxlab** [comment]
Sorry for the delay. Your code fix is in now.
