### ISSUE TITLE
Getting "Error: Index creation failed"

### ISSUE THREAD

**Issue by thepartisan101** [styxlab/next-cms-ghost#14]
Issue:
After cloning the repository on an EC2 instance running Ubuntu 20 and doing the "yarn dev" command, I get the following in the local server URL:
![image](https://user-images.githubusercontent.com/9511307/103637419-23b76200-4f54-11eb-877b-d5343c08dc12.png)

On the console:
`Error: Index creation failed.
    at getStaticProps (webpack-internal:///./pages/index.tsx:118:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

I thought it might be that I don't have any content to feed to the front end, so in ".env.local" I changed the default URL and API key for the ones pointing to a custom integration to an existing Ghost cms instance running on Lightsail. Still, same problem.

Could anyone point me out to what am I missing? Thanks

**Comment by styxlab** [comment]
This has most likely something to do with your EC2 instance. Could you add a `console.log(error)` statement before the `throw` statement and re-run again and post the output here?

**Comment by styxlab** [comment]
@thepartisan101: Is this issue still relevant?

**Comment by thepartisan101** [comment]
Hi, I managed to by using WSL on Windows, so didn't get to try your solution.
Forgot to close it.

**Comment by styxlab** [comment]
No problem. I will close it then.
