### ISSUE TITLE
No mouse horizontal scroll for the top panel 

### ISSUE THREAD

**Issue by StitiFatah** [styxlab/next-cms-ghost#142]
While having too many Primary Navigation Pages in the top panel (the one with a black background  that appears on Posts/pages and on the main index page while reaching a certain ScrollY value) the last ones just fades and are impossible to access. 
Same behavior on Chromium and Firefox but it's working fine on mobile ( tested on Brave on Android ). where you can still scroll. 

![Screenshot_2021-11-25_11-23-56](https://user-images.githubusercontent.com/68331131/143424373-c62f4fe5-fa1d-4697-8b75-51bc00fcff99.png)

Edit : I'm able to make it scroll when it has focus with the arrow keys, or by selecting the texts and continuing the motion to the right ( and left to go back ) but I don't think that's the intended way to do it.

**Comment by styxlab** [comment]
@StitiFatah: This repo uses the original Ghost style sheets, and this also doesn't work in the original Ghost theme as far as I remember. Thus it works "as designed". You can make your own fork of the repo and change whatever you like, but I don't want to deviate from the original here.

**Comment by StitiFatah** [comment]
That's probably what I'll end up doing since I also want to add some features. For the theme it makes sens, I just thought you rebuilt it from scratch.
