### ISSUE TITLE
Demo URL provided in Readme not working

### ISSUE THREAD

**Issue by tushargoyalofficial** [styxlab/next-cms-ghost#145]
I clicked on the demo URL in Readme file but it shows page not found. Can you please look into it or rectify it.

**Comment by styxlab** [comment]
I took the site temporarily off, because I am seeing an unusual amount of incoming traffic. Are you running a lot of tests against https://next.jamify.org?

**Comment by styxlab** [comment]
The site is up and running again.

**Comment by tushargoyalofficial** [comment]
> I took the site temporarily off, because I am seeing an unusual amount of incoming traffic. Are you running a lot of tests against https://next.jamify.org?

Nope, I just saw one article to create blazing fast web app, so I just wanted to see demo. That's it. I am a Senior Software developer, always looking out for new tech out there.

Thanks anyway.

**Comment by tushargoyalofficial** [comment]
> The site is up and running again.

Thank you very much...

**Comment by styxlab** [comment]
> Nope, I just saw one article to create blazing fast web app, so I just wanted to see demo. That's it. I am a Senior Software developer, always looking out for new tech out there.
> 
> Thanks anyway.

Thanks for the quick reply. Could you tell me the link of that article?

**Comment by tushargoyalofficial** [comment]
> > Nope, I just saw one article to create blazing fast web app, so I just wanted to see demo. That's it. I am a Senior Software developer, always looking out for new tech out there.
> > Thanks anyway.
> 
> Thanks for the quick reply. Could you tell me the link of that article?

Sure,

[https://reactjsexample.com/github-desktopofsamuel-ghost-nextjs/](url)

**Comment by tushargoyalofficial** [comment]
> > Nope, I just saw one article to create blazing fast web app, so I just wanted to see demo. That's it. I am a Senior Software developer, always looking out for new tech out there.
> > Thanks anyway.
> 
> Thanks for the quick reply. Could you give me the link to that article?

It was showing in my Google App Feeds.

**Comment by styxlab** [comment]
Thanks for the info! That actually explains the increased traffic since two days: [https://bestofreactjs.com/repo/desktopofsamuel-ghost-nextjs-react-nextjs-boilerplates](https://bestofreactjs.com/repo/desktopofsamuel-ghost-nextjs-react-nextjs-boilerplates).

**Comment by tushargoyalofficial** [comment]
> Thanks for the info! That actually explains the increased traffic since two days: https://bestofreactjs.com/repo/desktopofsamuel-ghost-nextjs-react-nextjs-boilerplates.

Hope this help you out...
You are doing great job... Thanks buddy
