### ISSUE TITLE
Changing theme settings doesn't work

### ISSUE THREAD

**Issue by Garfounkel** [styxlab/next-cms-ghost#147]
In the Ghost admin I tried changing some of the settings for the theme. For instance, I'd like the homepage to use the list feed layout rather than the dynamic grid. Changing (and saving) this setting from the Ghost admin doesn't impact the yarn instance running at localhost:3000. See screenshot below for the setting I'm trying to change:

![Screenshot_2](https://user-images.githubusercontent.com/10576004/147292755-a0d8c349-6e39-45e6-a18a-308659f9fc4c.png)

As I understand (please correct me if I'm wrong), this is by design since this repository is a template for a pre-built static site using the default casper theme (and settings). In that case, how would one go about generating a similar template using an arbitrary ghost theme?

**Comment by styxlab** [comment]
Welcome @Garfounkel: Yes, that's correct - next-cms-ghost is a front-end implementation of the Ghost Casper skin and uses Ghost in headless mode (which means changing styles in the CMS doesn't make sense).

If you only want to make changes to the stylesheets, you could alter `global.css` and `screen.css` to your needs (after forking the project). For more complex changes you might have to to change the react code as well.

**Comment by Garfounkel** [comment]
Sounds good, I'll give it a go. Thanks

**Comment by Garfounkel** [comment]
I made a fork modifying the theme to be as close as possible to the list feed setting. Here it is if that's of any interest for someone: https://github.com/Garfounkel/next-cms-ghost-list-feed

**Comment by styxlab** [comment]
Thanks! I am considering to support the list view with an additional option.
