### ISSUE TITLE
Netlify Deploy workflow fails

### ISSUE THREAD

**Issue by Garfounkel** [styxlab/next-cms-ghost#148]
Trying to deploy through Netflify using the deploy button from the readme ([![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=https://github.com/styxlab/next-cms-ghost&utm_source=github)) fails saying the directory "out_publish" wasn't found.

I also tried deploying this repo myself, from a fresh clone I ran the following commands:
```bash
git clone https://github.com/styxlab/next-cms-ghost.git
cd next-cms-ghost
yarn

# Development
yarn dev

# Production
yarn build

# Deploy
netlify deploy --prod
```
Which resulted in the same error.

**Comment by Garfounkel** [comment]
After a bunch of trial and error, I finally figured out how to deploy this repo on Netlify from a fresh clone.
```bash
git clone https://github.com/styxlab/next-cms-ghost.git
cd next-cms-ghost
yarn

# Development
yarn dev

# Production
yarn build

# Export a static site to /out directory
yarn export

# Rename the output folder, or change the config file at netlify.toml accordingly
mv out out_publish

# Deploy
netlify deploy --prod
```

I'm sure those steps are very basic, but for me having absolutely no experience with yarn/nextjs/netlify it wasn't all that easy to figure out. How about adding the full workflow to the readme?

**Comment by toreylittlefield** [comment]
@Garfounkel Thanks for the heads up because my deploy was failing as well. Did you update the `netlify.toml` to `build = "yarn export"`  and `publish = "out"` ? I tried deploying to netlify but it's erroring out. Might try removing the next-plugin but I am unsure how that'll affect the app.

![image](https://user-images.githubusercontent.com/52614742/148074184-eff949c2-540f-433a-b266-f1c30cf94103.png)

**Comment by Garfounkel** [comment]
> Did you update the netlify.toml to build = "yarn export" and publish = "out" ?

I haven't try deploying solely from Netlify's UI, but I think what you suggested should work. I would check if you can't specify somewhere in the Netlify UI that the build command is `yarn export`.

I also suggest trying to deploy manually if you haven't already:

> ```shell
> git clone https://github.com/styxlab/next-cms-ghost.git
> cd next-cms-ghost
> yarn
> 
> # Development
> yarn dev
> 
> # Export a static site to /out directory
> yarn export
> 
> # Rename the output folder, or change the config file at netlify.toml accordingly
> mv out out_publish
> 
> # Deploy
> netlify deploy --prod
> ```

**Comment by toreylittlefield** [comment]
@Garfounkel Thanks for the response. The manual deployment worked fine when I did it previously. In the Netlify UI you certainly can set the build commands but the `netlify.toml` will/should take priority and override anything set in the UI. 
I updated my as such but yeah running into that `Deploy failed due to an error in @netlify/plugin-nextjs plugin.` error. : 
```
[build]
  command = "yarn export"
  functions = "out_functions"
  publish = "out"

[build.environment]
  JAMIFY_NEXT_ISR = "false"
  JAMIFY_NEXT_FEATURE_IMAGES = "false"
  JAMIFY_NEXT_INLINE_IMAGES = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
 ```
  When I try to deploy without the plugins I get a different type error: 
  
  ```9:20:36 AM: > Build error occurred
9:20:36 AM: TypeError [ERR_INVALID_ARG_TYPE]: The "filename" argument must be of type string or an instance of URL. Received an instance of URL```

I'll see if I can solve it.

**Comment by toreylittlefield** [comment]
Just updating again that I've tried other configurations in the build process for netlify and removing the plugins for next but still always getting a build error. I am about to give up on this.

**Comment by styxlab** [comment]
Thanks for following up on this issue. I will have a look myself when I return from vacations.

Netlify changed and updated a bunch of things for Next.js deploys and this repo must be updated for that.

**Comment by toreylittlefield** [comment]
> Thanks for following up on this issue. I will have a look myself when I return from vacations.
> 
> Netlify changed and updated a bunch of things for Next.js deploys and this repo must be updated for that.
> 
> According to the Netlify docs, this repo needs at least 3 changes
> 
> 1. next.config.js: remove the line with `target: 'serverless'`
> 
> 2. Update plugin "@netlify/plugin-nextjs" to latest version 
> 
> 3. netlify.toml: update build directory to
> 
> ```
> [build]
> publish = ".next"
> ```
> 
> To get ISR and next/images working there are more changes needed, but those three might be sufficient to get the Netlify button working again.
> 

Thanks for following up. Happy new year. I think I scoured the Netlify docs and already attempted these changes you mentioned but it did not build.

 I believe it has to do with the next/images as you've said but I had a difficult time debugging that in the build log. I'll try your changes and report back my findings with the logs.

**Comment by styxlab** [comment]
PR #152 should fix the netlify deploy button. Things to note: 

- cache plugin is depreciated and now integrated into `@netlify/plugin-nextjs`
- plugin `@netlify/plugin-nextjs` is autodetected and can be removed from the `netlify.toml`
- I have also removed the function directory as functions should work out-of-the box now

Further work is needed on (1) next/images and (2) ISR. Both features are currently switched off on netlify builds. I will open new issues for both topics.

@toreylittlefield, @Garfounkel: Can you confirm that the netlify button is working for you as well?

**Comment by styxlab** [comment]
It fixed in my tests, so closing.
