### ISSUE TITLE
Open the images in full-screen display on click

### ISSUE THREAD

**Issue by dassiorleando** [styxlab/next-cms-ghost#162]
@styxlab,  This is more a **feature request/suggestion** than anything else.

The way the images work at the moment is great, I think it'll be even nicer to have them opened in full-screen (or at least in a wider way) on click on each.

Do let me know what you think about, please.

**Comment by styxlab** [comment]
I think that was already implemented on PR #158 by @laurentmmeyer.

**Comment by dassiorleando** [comment]
Maybe it works for simple images only **and not for galleries**?
Thanks for the reference.

**Comment by dassiorleando** [comment]
@styxlab @laurentmmeyer
Looks like it works only if we use Next Image Optimisation, or is there anything I missed somewhere?
I'm not using that feature at all.

**Comment by styxlab** [comment]
true, it only works for the NextImage component at the moment, but could be easily extended. May I ask you why you don't next/images? It usually has a big impact on loading speeds.

**Comment by dassiorleando** [comment]
I really like its impact but at the time I cloned your repository I was not a big fan of the structure of the generated URLs, I prefered the one I set up with my custom domain S3 side.
I may think about it even more today.

**Comment by styxlab** [comment]
Serving directly from S3 is not a good idea, you need a CDN to serve images from.

**Comment by dassiorleando** [comment]
Yes but I'm using CloudFront with the custom domain that I'm talking about.

**Comment by styxlab** [comment]
I don't intend to do anything about it in the near future as I think most people will use `next/images`. However, I am open to any PRs that extend the current solution to custom image optimizers. Please open a new case/PR if needed.
