### ISSUE TITLE
Can I change my theme. 

### ISSUE THREAD

**Issue by linbooks** [styxlab/next-cms-ghost#163]
If I change my default theme(casper), do I still get the features of next.js

**Comment by styxlab** [comment]
@linbooks Welcome to this projects. It depends of what you want to do.

`next-cms-ghost` is a front-end which means *it is* a theme, so changing it requires changing this project. There are many people who forked this project to change it to their needs and if it's a minor change it might be very easy to do. 

However, if you are looking for a completely different layout, you may end up changing quite a bit. So your mileage may vary. May I ask you what you are trying to achieve?
