### ISSUE TITLE
getting issue on author image

### ISSUE THREAD

**Issue by KunalSingh19** [styxlab/next-cms-ghost#181]
https://kunal.is-a.dev/ and https://kunal.is-a.dev/author/kunal

author image is not loading

**Comment by styxlab** [comment]
You need to add `ghost-production-98c0.up.railway.app` to the `IMAGE_DOMAINS`. See the [README](https://github.com/styxlab/next-cms-ghost#-nextjs-image-optimizations).

**Comment by KunalSingh19** [comment]
thanks it worked
