### ISSUE TITLE
I can't send message in Contact page

### ISSUE THREAD

**Issue by CarlosSpotFix** [styxlab/next-cms-ghost#185]
Hi, I'am trying to send a message when someone fills in the form on the contact page and it not work.

- **First error: 'Wrong origin. Check your siteUrl.'**. I update the **SiteURL** and solve it.
- **Second error: 'Sending message fail.'**. I don't know why.

Could help me, please?

Thanks

**Comment by styxlab** [comment]
You must four secret environment variables (similar to SiteURL):

EMAIL_TO
SMTP_HOST
SMTP_USER
SMTP_PASS

Therefore you need an SMTP account with appropriate credentials to get this feature to work.
