### ISSUE TITLE
Please explain clearly how to connect it with ghost cms

### ISSUE THREAD

**Issue by meanindra** [styxlab/next-cms-ghost#2]
Repository readme is too short. I don't understand how to connect it with ghost cms.

**Comment by styxlab** [comment]
Welcome @meanindra! 

You first create a content API keys in your Ghost CMS. The Content API URL and key can be obtained by creating a new Custom Integration under the Integrations screen in Ghost Admin.

Once you have the URL and key, you then link to them with one of the methods described in the [README](https://github.com/styxlab/next-cms-ghost#-ghost-content-api-keys).
