### ISSUE TITLE
Migrate to CSS-in-JS

### ISSUE THREAD

**Issue by arnaudjnn** [styxlab/next-cms-ghost#21]
Any recommendation to migrate to CSS-inJS solutions like chakra-ui I'm currently using in the rest of my codebase?

Does it sound interesting to do this work for the community?

**Comment by styxlab** [comment]
Welcome @arnaudjnn! This sounds really interesting! Here are my quick thoughts on this:

1. This project currently uses the _exact_ stylesheets as the Ghost Casper theme. That way I can assure it looks the same as the original and new updates can be incorporated by just updating the style sheets. With any CSS-inJS solution this property will be lost. Thus, I would rather open a new project than trying incorporate that here.

2.  I am open to opening a new variant of this project that uses an CSS-inJS solution. I would very much prefer to use TailwindCSS. My prerequisites for such a project would be a) A concept on how to easily swap themes which I think is not trivial especially for CSS-inJS solutions and b) A new theme which doesn't depend on Ghost Gasper, probably even simpler in styling so it is more a base theme for customized solutions.

**Comment by arnaudjnn** [comment]
Hello @styxlab,

Really enjoy what you've done here and totally agree with the fact you want to keep the same Casper stylesheet to keep the last updates.

**Comment by styxlab** [comment]
This project is a front-end replacement for headless Ghost, so you can quickly publish your blog sites statically (in fact hybrid) to a global CDN giving exceptional performance and security. As original Ghost, this is blog focused, maybe with some page additions like an About or Contact page. That way, the front-end is 100% React and no Handlebars is needed anymore.

If you already run a website and just want to add a blog to it, then keeping your blog separate from your main site is a good thing. Separating concerns is a successful pattern and I would not integrate your site and the blog into one Next.js app. This is not a website starter, but a blog starter.

**Comment by styxlab** [comment]
I am closing this for now. If you want to kick-off a new project, you can contact me on [twitter](https://twitter.com/jamifyjs).
