### ISSUE TITLE
Getting "Type error: Object is of type 'unknown'" while building the project

### ISSUE THREAD

**Issue by icy-meteor** [styxlab/next-cms-ghost#22]
I have added the environment variables both for local and production. The website works perfectly on development (localhost) but when I try building, it fails with the following error.

![image](https://user-images.githubusercontent.com/22114682/105198295-88350c80-5b63-11eb-999d-3f4a0bfcf9fd.png)

Any help would be appreciated :)

**Comment by icy-meteor** [comment]
Looks like the project doesn't like "npm" :(
Tried with yarn and it went through.

Closing the issue.

**Comment by styxlab** [comment]
This is not a problem with `npm` but with newer typescript package that was selected when you use `npm`. I get the same issue with `yarn` after updating to the latest typescript packages.

This problem needs to be fixed in the code.

**Comment by pitfritsch** [comment]
I just solved this error in my project, setted the Typescript flag _useUnknownInCatchVariables_ to false in tsconfig

Source: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#defaulting-to-the-unknown-type-in-catch-variables---useunknownincatchvariables

**Comment by styxlab** [comment]
@pitfritsch Thanks for your commet! The option is a quick fix and equivalent to introducting `any` types. I think it's better to cast the `unknown` type into your the expected error type. I made some code changes along those lines today.
