### ISSUE TITLE
Deploy to netlify is failing at build time

### ISSUE THREAD

**Issue by icy-meteor** [styxlab/next-cms-ghost#23]
Clicking the deploy to netlify button in the readme fails during build time.

![image](https://user-images.githubusercontent.com/22114682/105201499-f929f380-5b66-11eb-9edc-9f0354d52c84.png)

**Comment by styxlab** [comment]
@icy-meteor: Thanks for reporting. 

I can reproduce the issue and it lookls like an upstream bug: https://github.com/vercel/next.js/issues/20742. I will further look into how this can be fixed.
