### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by christianlauer** [styxlab/next-cms-ghost#3]
This happens when you try to open the admin backend:

Unhandled Runtime Error
Error: Failed to load static props

../../../../next-server/lib/router/router.ts (341:12) @ eval

  339 |       throw new Error(SSG_DATA_NOT_FOUND_ERROR)
  340 |     }
> 341 |     throw new Error(`Failed to load static props`)
      |          ^
  342 |   }
  343 |   return res.json()
  344 | })

**Comment by styxlab** [comment]
Welcome @christianlauer!

I have never seen this error, could you please link to an example repository and add a step-by-step description explaining how the error can be replicated?

**Comment by christianlauer** [comment]
First, thanks for taking the time to build such an amazing template! I'm new to JAMstack so I might be confused but tried to open http://localhost:3000/ghost for accessing the backend after following your instructions of the README. Installed it and can access it and also deploy it to vercel, but locally after "yarn dev" I tried to open http://localhost:3000/ghost and then the error occurred.

Merry Christmas, by the way :)

**Comment by dyljm1** [comment]
Having this issue as well -- thanks so much for creating this! 

<img width="695" alt="Screen Shot 2020-12-25 at 9 02 37 PM" src="https://user-images.githubusercontent.com/41519402/103144762-860e9800-46f4-11eb-9a0f-e22a7292fa87.png">

**Comment by BeatPlus** [comment]
If your development environment is run in Windows, there is a bug in Nextjs path rendering. #4 fixes this

**Comment by styxlab** [comment]
Let me clarify that this repo is a front-end replacement for Ghost but _not_ a back-end replacement. The idea is that you run a headless Ghost CMS instance where you create your articles and meta data. You can then use this repo to (statically + incrementally) create the visual views (currently Ghost Casper style) and easily publish your content on a global content delivery network (CDN) such as Vercel or Netlify. This architecture gives you a lot of benefits in terms of speed, customizations, global distribution and analytics.

If you do not have a Ghost instance running already, a good starting point is the article entitled [Ghost CMS on Hetzner Cloud](https://www.jamify.org/2020/04/07/ghost-cms-on-hetzner-cloud/) which I wrote a few months ago.

To answer you question: The endpoint `/ghost` does not exist here, you should go to your headless CMS instead. Nonetheless, you should get a _404 error_ when calling a non-existing endpoint and not an internal error - so this is something that needs to be fixed. I will open a new issue for that.

**Comment by christianlauer** [comment]
Sorry for the misunderstanding on my behalf here - I actually went to your gatsby version for the setup and it works fine. Cheers!
As this is the Casper theme, how much time do you think would somebody need to transform the https://edge.ghost.io/ Theme when they have your theme as a starting point?

**Comment by styxlab** [comment]
>  how much time do you think would somebody need to transform the https://edge.ghost.io/ Theme

For someone with good React knowledge, this should be doable within 2 - 3 weeks. There are some subtleties in the theme, such as the gallery views (sorted by hidden tags?)  and the slide show with next, previous, magnify, full screen etc. that may take some time to fully replicate.

**Comment by styxlab** [comment]
@all-contributors please add @christianlauer for bug reports
