### ISSUE TITLE
Alignment of images getting messed up

### ISSUE THREAD

**Issue by icy-meteor** [styxlab/next-cms-ghost#30]
After generating the content from my ghost blog, the alignment of images don't seem to be right. 
Also, the table of contents appears to go beneath the images.

Expected behaviour:

![image](https://user-images.githubusercontent.com/22114682/105482130-fbf32880-5ccd-11eb-8079-894be935d2a6.png)
Source: https://www.crio.do/blog/backend-development-career/

Current Behaviour: 

![image](https://user-images.githubusercontent.com/22114682/105482222-19c08d80-5cce-11eb-8661-7b7e8854228a.png)

**Comment by styxlab** [comment]
Temporary workaround:

```
// Table of Contents
export const toc: boolean = false
```
in `appConfig.js`.

This problem only exist when 

1. export const nextInlineImages: boolean = false AND
2. export const toc: boolean = true

A proper solution must be made in the 'toc' feature.

**Comment by styxlab** [comment]
Thanks for reporting. Please verify.

**Comment by icy-meteor** [comment]
Yes, this works.
But table of content continues to overlap. I'll disable it for now.

Also, my author and tag pages don't work. Is that how it is supposed to be?

**Comment by styxlab** [comment]
Wide and full screen images overlap the ToC by design, this is how it should be. With respect to author and tag pages, they are present but without the base path. There is a routing issue here, but don't know how to best solve this yet. Could you please publish your `routes.yaml` file that you use in your Ghost installation?

**Comment by styxlab** [comment]
Plaese open a new issue for every new topic.
