### ISSUE TITLE
Order of blog posts is not maintained

### ISSUE THREAD

**Issue by icy-meteor** [styxlab/next-cms-ghost#33]
The order of the blog posts is not the same as the original source.

Hosted version: https://next-cms-ghost-j2jwkzzdp.vercel.app/
![image](https://user-images.githubusercontent.com/22114682/105622977-06cbcb80-5e3c-11eb-9402-4dc86a34736a.png)

Original Source: https://www.crio.do
![image](https://user-images.githubusercontent.com/22114682/105622969-f156a180-5e3b-11eb-99d7-0ae29957eeec.png)

**Comment by styxlab** [comment]
Like the original Casper theme, this front-end orders posts according to publication date. However, it does respect the `Feature this post` flag. All posts with that flag take precedence over the publication date.

![image](https://user-images.githubusercontent.com/19638263/105626583-c74bb200-5e30-11eb-865f-bffb9e15bf65.png)

I therefore suspect that you have set the `Feature this post` flag for the first two posts shown. Just go into Ghost ADmin and take those flags out again (they won't have any effect on the original Casper theme anyways) and you should then see exactly the same ordering here.

**Comment by icy-meteor** [comment]
Yes, but if my posts are marked as "Featured" on Ghost, shouldn't they appear as featured in next-cms-ghost as well?

**Comment by styxlab** [comment]
The switch does not have any effect on the original Ghost Casper theme. But it has an effect here: it moves featured posts in front. That's how it should be.

**Comment by icy-meteor** [comment]
Okay, have unchecked `Feature this post` option on those blogs and updated them.
Still doesn't reflect on the next-cms-ghost project.

**Comment by styxlab** [comment]
It works. You need to re-build:
![image](https://user-images.githubusercontent.com/19638263/105627397-172d7780-5e37-11eb-8d83-f666103a605e.png)

**Comment by icy-meteor** [comment]
Ah got it. My bad, was trying in local but it wasn't updating.
Works now.
