### ISSUE TITLE
Author pages are getting incorrectly prefixed with /blog

### ISSUE THREAD

**Issue by icy-meteor** [styxlab/next-cms-ghost#34]
Getting a 404 page when I try visiting the author pages by clicking on them.

![image](https://user-images.githubusercontent.com/22114682/105622999-3975c400-5e3c-11eb-97f1-298df6da3e5b.png)

Hosted version: https://next-cms-ghost-j2jwkzzdp.vercel.app/blog/author/criodo

When I remove the /blog prefix and visit the link, it seems to work.
https://next-cms-ghost-j2jwkzzdp.vercel.app/author/criodo

**Comment by styxlab** [comment]
Currently this project assumes that you host your Ghost CMS under a (sub-)domain, such as `https://blog.crio.do` instead of `https://www.crio.do/blog`. The automatic link substitution does not yet work, if the CMS can only be reached under a subpath. I will fix it in the next release.

**Comment by styxlab** [comment]
Please verify if latest release fixes this problem for you too.

**Comment by styxlab** [comment]
Closing as solved.
