### ISSUE TITLE
Unable to make the /preview route work

### ISSUE THREAD

**Issue by mbernard** [styxlab/next-cms-ghost#36]
Am I supposed to be able to preview draft posts with this route?
I tried the post ID (GUID), the slug, and nothing seems to work.

**Comment by styxlab** [comment]
@mbernard: Welcome!

The preview route has the following access pattern `/api/v1/preview/<slug>`.

**Comment by mbernard** [comment]
hummm
It works for a published post, but when I try with a draft I got a 404
Am I doing something wrong? any ideas?

**Comment by styxlab** [comment]
That's a current limitation as the Ghost Content API does not expose draft posts.

There are possible workarounds, such as accessing the Ghost Admin endpoints, but it doesn't quite fit into the current access patterns. If you want to PR that, you are more than welcome.

**Comment by mbernard** [comment]
Thanks for the clarification

**Comment by nring** [comment]
@styxlab Checking in a year later, do you still see this as a limitation of the Ghost Content API? And that the best way to preview unpublished posts is likely through something custom with Ghost Admin endpoints?

**Comment by styxlab** [comment]
@nring Yes, the Ghost Content API limitation remains and you would have to make requests through the Ghost Content API. I have no plans to add that myself, but if you want to make a contribution you are more than welcome.
