### ISSUE TITLE
Cannot see Portal button for adding members/paying subscriptions.

### ISSUE THREAD

**Issue by thepartisan101** [styxlab/next-cms-ghost#38]
When setting up the Portal in the Ghost Admin I cannot see it in the Next js front-end.
Is this a plugin not yet supported?

**Comment by styxlab** [comment]
The membership function currently supported is the email signup. Everything related to restricted content / paying subscription is not supported. There are currently no plans on my side to integrate those paywalls, but I would support PRs that go into that direction.

**Comment by thepartisan101** [comment]
Understood. I need that for one of my projects so I'll move it to the hosted Ghost for now. I guess if I wanted to do PR for that I'd have to replicate the front end buttons, plus the Stripe elements to build the form, and probably look into an exported ghost blog in json to find where the portal info is injected?

**Comment by styxlab** [comment]
Yes, if you want to PR that functionality, you'd have to:

- make a theme variant like Lyra (for the additional buttons, etc.)
- add an authentication method (such as next-auth)
- Link next-auth users to ghost members in your Ghost CMS
- All the stripe stuff could be handled within Ghost CMS
- Hide/show posts according to membership status

This is all possible, but I would wait until Ghost release REST support for membership functions in their Admin API.

**Comment by thepartisan101** [comment]
Great, thanks for the breakdown.

I'll wait for the REST release then.
