### ISSUE TITLE
Navigation slow on development

### ISSUE THREAD

**Issue by muhajirdev** [styxlab/next-cms-ghost#45]
It seems like the navigation is a bit slow when we're in development mode.

Why is it?

How to reproduce
* Clone this repo
* yarn dev
* Try click one of the post. It will take a few seconds before new page loaded

**Comment by styxlab** [comment]
This is expected in dev mode and inherent to the way Next.js works. When you watch your console output, you'll see a message `wait - compiling...`, so the site is re-generating. This allows for hot-reloading which is what most people want in dev mode. In addition to the initial compile step, every static page is also [re-rendered on every request](https://nextjs.org/docs/basic-features/data-fetching#runs-on-every-request-in-development) in development. Your actual slowness, however, also depends on the capabilities of your development environment (2 seconds is normal on fast machines for the initial request). Most important: Sites are blazing fast in production.

**Comment by styxlab** [comment]
Closed as answered. As always, this issue can be re-opened on request.
