### ISSUE TITLE
Index SiteNav is not sticky

### ISSUE THREAD

**Issue by marsflow** [styxlab/next-cms-ghost#49]
Hello @styxlab,

I found that index menu is not sticky on scrolling. 
<img width="1591" alt="Screen Shot 2021-02-15 at 05 56 06" src="https://user-images.githubusercontent.com/7637037/108027892-76109600-705d-11eb-9dbe-8ea25173905a.png">

I'll try to make a pull request of it. Thank you

**Comment by styxlab** [comment]
@all-contributors please add @marsflow for code
