### ISSUE TITLE
How to add a new template to the Ghost CMS and reflect on front-end? 

### ISSUE THREAD

**Issue by machinelearnear** [styxlab/next-cms-ghost#53]
Hi,

I'm running an instance of Ghost on AWS Lightsail together with this repo deployed to Vercel. Connection between the two works fine with the instructions in the README and I added an additional webhook so that every update in the content (e.g. new post) gets a new build started on Vercel. Now, I would like to change my current template and install a new one. I can do that on the Ghost CMS and see the changes but not on the front-end. How should I do that?

Thank you very much!

**Comment by styxlab** [comment]
Welcome @machinelearnear! Cool that you are running your site with this repo. I must disappoint you now: this repo uses Ghost as a `headless` CMS: this means changing themes (i.e. the `head`) on Ghost CMS has zero effect here.

Currently this repo only supports one theme which is a Ghost Casper clone.

**Comment by nicolasmetallo** [comment]
Thanks! It's like I was missing some important bit of info about how Ghost API actually worked there 😄  For anyone looking at this, [this](https://ghost.org/changelog/jamstack/?_ga=2.63299883.522229917.1613665938-1953069401.1613145417) is a good place to start. 

Any advice/tips on how to port a new theme? I know there's a lot of work already done when you ported Casper.

Thank you again for the great work!

**Comment by styxlab** [comment]
The answer to your questions depends on what you want to achieve. A rough guidance would be:

1. If you want to make minor changes with no or little styling, such as extending the header or footer the best is to add a new option to this repository. Have a look at the `customNavigation` option to get an idea how this could be done. PRs are welcome.

2. If you just want to tweak styles but stay close to the original theme, you can simply swap `stylesheets` under the `styles` folder. Even better is to add your own themes which only override some parts of the existing `screen.css`. To get an idea how this can be accomplished have a look at `styles/prism.css` or `styles/toc.css`. 

3. If you want a completely new theme, with different animations, toolbars etc. then you would also need to change React component logic. In this case, I recommend you create your own `fork` and us this repository as a boilerplate for your own, fully customized version.

**Comment by styxlab** [comment]
Closing as answered. As always, this thread can be re-opened if needed.
