### ISSUE TITLE
Support for Ghost v4?

### ISSUE THREAD

**Issue by Buda9** [styxlab/next-cms-ghost#60]
Hello :) Just wondering if (and when) you're going to add support for latest version of Ghost? Thanks and keep up a good work!

**Comment by styxlab** [comment]
I migrated my Ghost CMS to v4 and did not find any incompatibilities with next-cms-ghost. That's the beauty of running a headless setup - it works out of the box. Anything missing?

**Comment by Buda9** [comment]
You're totally correct. My wordpress imported content is causing many issues, probably because it's multilingual. I've deleted content and created few articles inside Ghost, and it's working perfectly. Thank you for your prompt response :)

**Comment by mikestecker** [comment]
I changed the api version in `lib/ghost.ts` to `v4`, only getting a typing error but I know [the SDK was updated](https://github.com/TryGhost/SDK/commit/2986ceb275b24ecdecd39b03ed38f085adb3248f) to support it. I have [posted an issue to request an update](https://github.com/TryGhost/SDK/issues/378) to the typings.

**Comment by styxlab** [comment]
@mikestecker: Thanks a lot for reporting. I am going to wait with the update until correct typings are available upstream. A current workaround could be to change it to 'canary':

```
const api = new GhostContentAPI({
  url: ghostAPIUrl,
  key: ghostAPIKey,
  version: 'canary',
})
```
However, the new version doesn't give you anything new, until exposes new endpoints or functionality in `v4`. I expect most changes in the `v4 Admin API` not the `v4 Content API`. What functionality are you missing that is only available in `v4`?

**Comment by mikestecker** [comment]
> What functionality are you missing that is only available in `v4`?

Nothing that I'm aware of, I just wanted to change it for my own sanity knowing I'm on v4 running Ghost 4.x 😂

**Comment by styxlab** [comment]
Okay, I'll update to Content API `v4` if

 1. typings are available and the Ghost JS client API fully supports it
 2. this repo needs a feature that is only available in `v4`
 3. Backwards compatibility is ensured (solution could be to try `v4` first and use `v3` as a fallback if it does not succeed).

I close this for now, but please reply to this thread if 1.) or 2.) becomes relevant.
