### ISSUE TITLE
og:title not working correctly

### ISSUE THREAD

**Issue by Buda9** [styxlab/next-cms-ghost#61]
It crawls site title instead of article title, example: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fnext.jamify.org%2Fthe-editor

og:title | Gotsby Demo

but it should be:

og:title | Writing posts with Ghost

**Comment by styxlab** [comment]
Fixed on latest version. Please confirm.

**Comment by styxlab** [comment]
@all-contributors please add @Buda9 for bug

**Comment by Buda9** [comment]
Yes, perfect! I can confirm it's working now. And many thanks for adding me to the contributors list :)
