### ISSUE TITLE
How to modify taxonomy?

### ISSUE THREAD

**Issue by mikestecker** [styxlab/next-cms-ghost#64]
Question: how can I modify the taxonomy of my posts?

I'd like to change my routes to `/news/[year]/[slug]`

**Comment by styxlab** [comment]
Moving everything to a subdirectory (e.g. `/news/` or `/blog/`) should be done with Next.js `basePath` feature which is simply a configuration option in `next.config.js`. Taxonomy changes like adding a year should be made in your Ghost CMS (with routes.yaml). They are automatically picked up by this repo! An exception to this rule are `collections` which can be configured in `routesConfig.ts`.

**Comment by mikestecker** [comment]
Gotcha, thanks for the tips!

I don't want to move everything to a subdirectory, so what I ended up doing was:

In `routesConfig.ts`:
```typescript
export const collections: Collection<GhostPostOrPage>[] = [
  {
    path: `events`,
    selector: node => node.primary_tag && node.primary_tag.slug === `event`
  },
  {
    path: `news`,
    selector: node => !node.primary_tag || node.primary_tag && node.primary_tag.slug !== `event`
  },
]
```

In Ghosts's `routes.yaml`:
```yaml
collections:
  /:
    permalink: /{year}/{slug}/
    template: index
```

So far so good. I haven't tested to make sure the page links aren't screwed up though... I'm putting my page links in manually in the header/footer nav though.

**Comment by timuster** [comment]
@styxlab I opened #68 as the `basePath` does not seem to work.
