### ISSUE TITLE
Error: ENAMETOOLONG: name too long when deploying to Vercel

### ISSUE THREAD

**Issue by simhol** [styxlab/next-cms-ghost#69]
Apparently, some post images coming in via Unsplash generate filenames that are too long. It doesn't happen with every image though, but for this specific one:

https://images.unsplash.com/flagged/photo-1563536314719-2e812e896f50?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80

Error message from Vercel:
Could not write to file cache. This is expected during ISR, but not during deploy. Error: ENAMETOOLONG: name too long, open '/vercel/workpath0/.cache/https%3A%2F%2Fimages.unsplash.com%2Fflagged%2Fphoto-1563536310477-c7b4e3a800c2%3Fcrop%3Dentropy%26cs%3Dtinysrgb%26fit%3Dmax%26fm%3Djpg%26ixid%3DMnwxMTc3M3wwfDF8c2VhcmNofDQxfHxwcm9ncmFtbWVyfGVufDB8fHx8MTYxNzYwNTE4Mw%26ixlib%3Drb-1.2.1%26q%3D80%26w%3D2000.txt'

**Comment by styxlab** [comment]
Would it be possible to remove `ixid` and `ixlib` tags?

**Comment by styxlab** [comment]
> Would it be possible to remove `ixid` and `ixlib` tags?

Okay, seems it is required by unsplash to conform to their API, quote "The API returns image URLs containing an ixid parameter. All resizing and manipulations of image URLs must keep this parameter as it allows for your application to report photo views and be compliant with the API Guidelines."

**Comment by styxlab** [comment]
ENAMETOOLONG error comes from the OS file system restrictions, which stems from Vercel's current system. There is nothing I can do to change here as this needs to be solved upstream at Vercel (maybe you want to open an issue there?).

However, I will look into ways to compress the urls, so they fit into the current boundaries.

**Comment by simhol** [comment]
Awesome, for now, I just took another image,. If it happens again with other images I will contact Vercel and see what they have to say about it.

**Comment by styxlab** [comment]
@all-contributors please add @simhol for bug

**Comment by styxlab** [comment]
Identified the root cause: I was using the full URI encoded url for the cache key, which can get rather long and potentially lead to the  ENAMETOOLONG error. The solution is to calculate a hash with a pre-defined length for the cache keys, which should solve the issue. Could you please test your previously failing image with the latest `next-cms-ghost` version in order to verify that the issue is indeed fixed?

**Comment by simhol** [comment]
Sure, will do!

**Comment by simhol** [comment]
It works, awesome :) Thanks a lot!
