### ISSUE TITLE
Normalization not working on Windows

### ISSUE THREAD

**Issue by styxlab** [styxlab/next-cms-ghost#7]
@BeatPlus moved your comment to a new issue:

If your development environment is run in Windows, there is a bug in Nextjs path rendering. #4 fixes this

**Comment by styxlab** [comment]
This project actively supports Linux and WSL (Windows Subsystem for Linux), so I am not yet sure how much effort I can put into Windows. I'd be surprised if #4 is the only change needed to make things work on native Windows. There might be other places in the code, where fore-slashes are used (there are also calls to the file-system).

Therefore, before merging this PR I'd like to get a better overview what is needed here to fully support Windows. If you could identify the places that need to be changed/checked: that would be great. I also welcome any proposals on how this repo can sustainably support Windows, maybe we need to implement some automatic tests for that?

**Comment by BeatPlus** [comment]
Thanks @styxlab , I  managed to get my development environment running but your guess that something else must be broken is valid. I will migrate to WSL but I will commit in this PR additional bug fixes that I spot

**Comment by styxlab** [comment]
@BeatPlus Super that you can give WSL a try - it's a much better experience when working with this repo but also with other nodejs driven applications. I will close the PR, but you can always open a new issue (or PR) for your upcoming findings.
