### ISSUE TITLE
No Ghost Admin Panel?

### ISSUE THREAD

**Issue by icueMike** [styxlab/next-cms-ghost#73]
Im new to the whole deployment to cloud even with ghost. I have it deployed successfully, however, I am confused if there is an admin panel like `domain.com/ghost/` or not. Else, how do we make posts and what-not?

**Comment by styxlab** [comment]
Welcome @icueMike! You need to set up a headless Ghost instance. I've described how to setup Ghost on [Hetzner Cloud](https://www.jamify.org/2020/04/07/ghost-cms-on-hetzner-cloud/), but this is just one self-hosted option and you'll find a lot of tutorials on the web if you want to set it up on digitalocean, heroku or with any other provider.

**Comment by icueMike** [comment]
ica n setup 1 on https://www.digitalpress.blog if that will work and thank you for the welcoming :)

**Comment by styxlab** [comment]
Thanks for sharing. Do they allow to run your Ghost instance in headless mode?

**Comment by icueMike** [comment]
no, its a full installation actually

**Comment by icueMike** [comment]
its also free ghost hosting

**Comment by styxlab** [comment]
If it's a full, unrestricted Ghost installation it should be possible to run it in headless mode. Only then will you be able to use this repository and make use of the static site benefits.
