### ISSUE TITLE
Image optimization option causes ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by styxlab** [styxlab/next-cms-ghost#76]
Note: Moved this issue to a new thread. Originally posted by @simhol, quote;

Hey @styxlab,

thanks again for taking yourtime with me, much appreciated.

When I run the repo in demo mode, I immediately get 

![image](https://user-images.githubusercontent.com/4987937/115142809-0eb69880-a044-11eb-8576-b9e395710ed0.png)

in my browser console and images don't show.

This is probably not related but an issue nonetheless :)

**Comment by styxlab** [comment]
Not by @simhol, quote:  Ah this goes away if I set export const nextFeatureImages: boolean = false

**Comment by styxlab** [comment]
@simhol: Did you add all domains for your images in `next.config.js` as described in the README?

**Comment by simhol** [comment]
I've tested this on another machine. Works fine. I will try to investigate further!

**Comment by styxlab** [comment]
Probably unrelated but who knows: https://github.com/vercel/vercel/issues/6126

**Comment by styxlab** [comment]
@simhol: Is this issue still relevant?

**Comment by styxlab** [comment]
Closing as not reproducable. If you disagree, please link to a repository with a reproducable example and add some instructions to it.
