### ISSUE TITLE
Unable to make changes to website using ghost

### ISSUE THREAD

**Issue by arnish12345** [styxlab/next-cms-ghost#78]
Hi ! I am to newbie but I spent countless hours to recreate **_[THIS](https://www.jamify.org/2020/07/15/running-a-professional-blog-for-free/)_** using VERCEL (netlify doesn't work for me) and NEXT.JS . I followed all the relevant steps but I am still unable to  unable to make changes to the **_[WEBSITE](https://nex.vercel.app/)_** using ghost. I can see the changes I made on localhost:3000 but when I build and deploy it (yarn build & vercel --prod), everything remains same.

**Comment by styxlab** [comment]
When you deploy to a provider like Vercel, you must set environment variables as described in the [README](https://github.com/styxlab/next-cms-ghost#-ghost-content-api-keys).

**Comment by arnish12345** [comment]
Build Logs

02:24:20.355  	Retrieving list of deployment files...
02:24:21.918  	Downloading 113 deployment files...
02:24:22.480  	Analyzing source code...
02:24:23.697  	Installing build runtime...
02:24:25.772  	Build runtime installed: 2.075s
02:24:28.522  	Looking up build cache...
02:24:28.565  	Build cache not found
02:24:29.842  	Installing dependencies...
02:24:30.188  	yarn install v1.22.10
02:24:30.253  	[1/4] Resolving packages...
02:24:30.496  	[2/4] Fetching packages...
02:24:41.409  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
02:24:41.410  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
02:24:41.436  	[3/4] Linking dependencies...
02:24:49.323  	[4/4] Building fresh packages...
02:24:49.700  	Done in 19.52s.
02:24:49.724  	Detected Next.js version: 10.2.0
02:24:49.727  	Running "yarn run build"
02:24:49.996  	yarn run v1.22.10
02:24:50.023  	$ next build
02:24:50.651  	info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
02:24:50.764  	info  - Checking validity of types...
02:24:50.778  	Attention: Next.js now collects completely anonymous telemetry regarding usage.
02:24:50.778  	This information is used to shape Next.js' roadmap and prioritize features.
02:24:50.778  	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
02:24:50.778  	https://nextjs.org/telemetry
02:25:00.532  	info  - Creating an optimized production build...
02:25:18.297  	info  - Compiled successfully
02:25:18.297  	info  - Collecting page data...
02:25:19.188   **> Build error occurred
02:25:19.190  	Error: Request failed with status code 404
02:25:19.190  	    at createError (/vercel/path0/node_modules/axios/lib/core/createError.js:16:15)
02:25:19.190  	    at settle (/vercel/path0/node_modules/axios/lib/core/settle.js:17:12)
02:25:19.190  	    at IncomingMessage.handleStreamEnd (/vercel/path0/node_modules/axios/lib/adapters/http.js:260:11)
02:25:19.190  	    at IncomingMessage.emit (events.js:327:22)
02:25:19.190  	    at endReadableNT (internal/streams/readable.js:1327:12)
02:25:19.190  	    at processTicksAndRejections (internal/process/task_queues.js:80:21)** {
02:25:19.190  	  type: 'Error',
02:25:19.190  	  config: {
02:25:19.190  	    url: 'https://cms.nex.vercel.app/ghost/api/v3/content/authors/',
02:25:19.190  	    method: 'get',
02:25:19.190  	    headers: {
02:25:19.190  	      Accept: 'application/json, text/plain, */*',
02:25:19.191  	      'User-Agent': 'axios/0.21.1'
02:25:19.191  	    },
02:25:19.191  	    params: {
02:25:19.191  	      key: '1094ae959af581ea7ad558d944',
02:25:19.191  	      limit: 'all',
02:25:19.191  	      include: 'count.posts'
02:25:19.191  	    },
02:25:19.191  	    transformRequest: [ null ],
02:25:19.191  	    transformResponse: [ null ],
02:25:19.191  	    timeout: 0,
02:25:19.191  	    xsrfCookieName: 'XSRF-TOKEN',
02:25:19.191  	    xsrfHeaderName: 'X-XSRF-TOKEN',
02:25:19.191  	    maxContentLength: -1,
02:25:19.191  	    maxBodyLength: -1
02:25:19.191  	  }
02:25:19.191  	}
02:25:19.246  	error Command failed with exit code 1.
02:25:19.246  	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
02:25:19.265  	Error: Command "yarn run build" exited with 1

**Comment by styxlab** [comment]
This looks like a mis-configuration. Could you please post your Ghost content API keys here?

**Comment by arnish12345** [comment]
1094ae959af581ea7ad558d944

**Comment by styxlab** [comment]
I also need the Ghost Content API URL.

**Comment by arnish12345** [comment]
http://localhost:2368

**Comment by styxlab** [comment]
Ah, now I understand what you are up to. The article you are referencing uses Gatsby + Netlify.

I am not sure whether you can do locally built deploys with NextJS + Vercel. Currently, I only support publicly available Ghost CMS in connection with this repo. 

I recommend you to set up a Ghost CMS with Hetzner Cloud as described in the first article on jamify.org. An alternative could be to host your Ghost CMS on Heroku.

**Comment by arnish12345** [comment]
I tried Heroku first it but it could not verify my credit cards. Is deploying locally built next.js supported on Netlify ?

**Comment by styxlab** [comment]
I haven't tried that combination yet, so I can't tell. You may wish to contact Netlify support or their support forum to find out.

**Comment by arnish12345** [comment]
Now I am trying AWS + Netlify, still same issue.
I pressed deploy to Netlify button on your repo.
Let me know if you notice any mis-configuration.

GHOST (AWS):
API URL : http://ec2-65-0-80-107.ap-south-1.compute.amazonaws.com
Content API key : 89d90a1b2f7b4d63dd9b74024b

SITE (NETLIFY):
CMS_GHOST_API_KEY : 89d90a1b2f7b4d63dd9b74024b
CMS_GHOST_API_URL : http://cms.ec2-65-0-80-107.ap-south-1.compute.amazonaws.com
SITE_URL : https://www.tender-hoover-6b996c.netlify.app

Actual Site : https://tender-hoover-6b996c.netlify.app

Build gets triggered using Build Hooks but I think it fails to build.

BUILD LOGS :
2:16:41 PM: Build ready to start
2:16:43 PM: build-image version: e4d2dbe4cfec46db257e869258461ded89b75c9b
2:16:43 PM: build-image tag: v3.7.3
2:16:43 PM: buildbot version: 2cb5794cb93042dadefe5dbdc6b35edc34c20454
2:16:43 PM: Fetching cached dependencies
2:16:43 PM: Starting to download cache of 188.9MB
2:16:44 PM: Finished downloading cache in 1.112395684s
2:16:44 PM: Starting to extract cache
2:16:51 PM: Finished extracting cache in 7.024479102s
2:16:51 PM: Finished fetching cache in 8.190978447s
2:16:51 PM: Starting to prepare the repo for build
2:16:51 PM: Preparing Git Reference refs/heads/master
2:16:52 PM: Parsing package.json dependencies
2:16:53 PM: Starting build script
2:16:54 PM: Installing dependencies
2:16:54 PM: Python version set to 2.7
2:16:54 PM: Started restoring cached node version
2:16:57 PM: Finished restoring cached node version
2:16:57 PM: v12.18.0 is already installed.
2:16:58 PM: Now using node v12.18.0 (npm v6.14.4)
2:16:58 PM: Started restoring cached build plugins
2:16:58 PM: Finished restoring cached build plugins
2:16:58 PM: Attempting ruby version 2.7.1, read from environment
2:17:00 PM: Using ruby version 2.7.1
2:17:00 PM: Using PHP version 5.6
2:17:00 PM: Started restoring cached yarn cache
2:17:00 PM: Finished restoring cached yarn cache
2:17:00 PM: NETLIFY_YARN_WORKSPACES feature flag set
2:17:01 PM: {"type":"error","data":"Cannot find the root of your workspace - are you sure you're currently in a workspace?"}
2:17:01 PM: No workspace detected
2:17:01 PM: Started restoring cached node modules
2:17:01 PM: Finished restoring cached node modules
2:17:01 PM: Installing NPM modules using Yarn version 1.22.4
2:17:01 PM: yarn install v1.22.4
2:17:01 PM: [1/4] Resolving packages...
2:17:02 PM: success Already up-to-date.
2:17:02 PM: Done in 0.46s.
2:17:02 PM: NPM modules installed using Yarn
2:17:02 PM: Started restoring cached go cache
2:17:02 PM: Finished restoring cached go cache
2:17:02 PM: go version go1.14.4 linux/amd64
2:17:02 PM: go version go1.14.4 linux/amd64
2:17:02 PM: Installing missing commands
2:17:02 PM: Verify run directory
2:17:04 PM: ​
2:17:04 PM: ────────────────────────────────────────────────────────────────
2:17:04 PM:   Netlify Build                                                 
2:17:04 PM: ────────────────────────────────────────────────────────────────
2:17:04 PM: ​
2:17:04 PM: ❯ Version
2:17:04 PM:   @netlify/build 11.5.1
2:17:04 PM: ​
2:17:04 PM: ❯ Flags
2:17:04 PM:   deployId: 608fb871b42fb0c3d9535d87
2:17:04 PM: ​
2:17:04 PM: ❯ Current directory
2:17:04 PM:   /opt/build/repo
2:17:04 PM: ​
2:17:04 PM: ❯ Config file
2:17:04 PM:   /opt/build/repo/netlify.toml
2:17:04 PM: ​
2:17:04 PM: ❯ Context
2:17:04 PM:   production
2:17:04 PM: ​
2:17:04 PM: ❯ Loading plugins
2:17:04 PM:    - @netlify/plugin-nextjs@3.0.3 from netlify.toml
2:17:04 PM:    - netlify-plugin-cache-nextjs@1.4.0 from netlify.toml
2:17:04 PM: ​
2:17:04 PM: ────────────────────────────────────────────────────────────────
2:17:04 PM:   1. onPreBuild command from @netlify/plugin-nextjs             
2:17:04 PM: ────────────────────────────────────────────────────────────────
2:17:04 PM: ​
2:17:05 PM: info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
2:17:05 PM: ​
2:17:05 PM: (@netlify/plugin-nextjs onPreBuild completed in 593ms)
2:17:05 PM: ​
2:17:05 PM: ────────────────────────────────────────────────────────────────
2:17:05 PM:   2. onPreBuild command from netlify-plugin-cache-nextjs        
2:17:05 PM: ────────────────────────────────────────────────────────────────
2:17:05 PM: ​
2:17:06 PM: Restored the cached .next folder at the location `.next/cache`
2:17:06 PM: ​
2:17:06 PM: (netlify-plugin-cache-nextjs onPreBuild completed in 736ms)
2:17:06 PM: ​
2:17:06 PM: ────────────────────────────────────────────────────────────────
2:17:06 PM:   3. build.command from netlify.toml                            
2:17:06 PM: ────────────────────────────────────────────────────────────────
2:17:06 PM: ​
2:17:06 PM: $ yarn build
2:17:06 PM: yarn run v1.22.4
2:17:06 PM: $ next build
2:17:07 PM: info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
2:17:07 PM: info  - Checking validity of types...
2:17:22 PM: info  - Creating an optimized production build...
2:17:30 PM: (node:1436) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
2:17:33 PM: warn  - Compiled with warnings
2:17:33 PM: ./node_modules/crypto-hash/index.js
2:17:33 PM: Critical dependency: the request of a dependency is an expression
2:17:33 PM: ./node_modules/next/dist/next-server/server/load-components.js
2:17:33 PM: Critical dependency: the request of a dependency is an expression
2:17:33 PM: ./node_modules/next/dist/next-server/server/load-components.js
2:17:33 PM: Critical dependency: the request of a dependency is an expression
2:17:33 PM: ./node_modules/next/dist/next-server/server/load-components.js
2:17:33 PM: Critical dependency: the request of a dependency is an expression
2:17:33 PM: ./node_modules/next/dist/next-server/server/require.js
2:17:33 PM: Critical dependency: the request of a dependency is an expression
2:17:33 PM: ./node_modules/next/dist/next-server/server/require.js
2:17:33 PM: Critical dependency: the request of a dependency is an expression
2:17:33 PM: ./node_modules/next/dist/next-server/server/require.js
2:17:33 PM: Critical dependency: the request of a dependency is an expression
2:17:33 PM: info  - Collecting page data...
2:17:36 PM: > Build error occurred
2:17:36 PM: Error: getaddrinfo ENOTFOUND cms.ec2-65-0-80-107.ap-south-1.compute.amazonaws.com
2:17:36 PM:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
2:17:36 PM:   type: 'Error',
2:17:36 PM:   config: {
2:17:36 PM:     url: 'http://cms.ec2-65-0-80-107.ap-south-1.compute.amazonaws.com/ghost/api/v3/content/tags/',
2:17:36 PM:     method: 'get',
2:17:36 PM:     headers: {
2:17:36 PM:       Accept: 'application/json, text/plain, */*',
2:17:36 PM:       'User-Agent': 'axios/0.21.1'
2:17:36 PM:     },
2:17:36 PM:     params: {
2:17:36 PM:       key: '****',
2:17:36 PM:       limit: 'all',
2:17:36 PM:       include: 'count.posts'
2:17:36 PM:     },
2:17:36 PM:     transformRequest: [ null ],
2:17:36 PM:     transformResponse: [ null ],
2:17:36 PM:     timeout: 0,
2:17:36 PM:     xsrfCookieName: 'XSRF-TOKEN',
2:17:36 PM:     xsrfHeaderName: 'X-XSRF-TOKEN',
2:17:36 PM:     maxContentLength: -1,
2:17:36 PM:     maxBodyLength: -1
2:17:36 PM:   },
2:17:36 PM:   code: 'ENOTFOUND'
2:17:36 PM: }
2:17:37 PM: error Command failed with exit code 1.
2:17:37 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2:17:37 PM: ​
2:17:37 PM: ────────────────────────────────────────────────────────────────
2:17:37 PM:   "build.command" failed                                        
2:17:37 PM: ────────────────────────────────────────────────────────────────
2:17:37 PM: ​
2:17:37 PM:   Error message
2:17:37 PM:   Command failed with exit code 1: yarn build
2:17:37 PM: ​
2:17:37 PM:   Error location
2:17:37 PM:   In build.command from netlify.toml:
2:17:37 PM:   yarn build
2:17:37 PM: ​
2:17:37 PM:   Resolved config
2:17:37 PM:   build:
2:17:37 PM:     command: yarn build
2:17:37 PM:     commandOrigin: config
2:17:37 PM:     environment:
2:17:37 PM:       - CMS_GHOST_API_KEY
2:17:37 PM:       - CMS_GHOST_API_URL
2:17:37 PM:       - INCOMING_HOOK_BODY
2:17:37 PM:       - INCOMING_HOOK_TITLE
2:17:37 PM:       - INCOMING_HOOK_URL
2:17:37 PM:       - SITE_URL
2:17:37 PM:       - JAMIFY_NEXT_ISR
2:17:37 PM:       - JAMIFY_NEXT_FEATURE_IMAGES
2:17:37 PM:       - JAMIFY_NEXT_INLINE_IMAGES
2:17:37 PM:     publish: /opt/build/repo/out_publish
2:17:37 PM:   functionsDirectory: /opt/build/repo/out_functions
2:17:37 PM:   plugins:
2:17:37 PM:     - inputs: {}
2:17:37 PM:       origin: config
2:17:37 PM:       package: '@netlify/plugin-nextjs'
2:17:37 PM:     - inputs: {}
2:17:37 PM:       origin: config
2:17:37 PM:       package: netlify-plugin-cache-nextjs
2:17:37 PM: Caching artifacts
2:17:37 PM: Started saving node modules
2:17:37 PM: Finished saving node modules
2:17:37 PM: Started saving build plugins
2:17:37 PM: Finished saving build plugins
2:17:37 PM: Started saving yarn cache
2:17:37 PM: Finished saving yarn cache
2:17:37 PM: Started saving pip cache
2:17:37 PM: Finished saving pip cache
2:17:37 PM: Started saving emacs cask dependencies
2:17:37 PM: Finished saving emacs cask dependencies
2:17:37 PM: Started saving maven dependencies
2:17:37 PM: Finished saving maven dependencies
2:17:37 PM: Started saving boot dependencies
2:17:37 PM: Finished saving boot dependencies
2:17:37 PM: Started saving rust rustup cache
2:17:37 PM: Finished saving rust rustup cache
2:17:37 PM: Started saving go dependencies
2:17:37 PM: Finished saving go dependencies
2:17:37 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
2:17:37 PM: Creating deploy upload records
2:17:37 PM: Failing build: Failed to build site
2:17:37 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
2:17:37 PM: Finished processing build request in 54.909516799s

**Comment by styxlab** [comment]
Your `CMS_GHOST_API_URL` is wrong. There is an addition "cms" prefix and the given site is not known. According to the above description, the correct `CMS_GHOST_API_URL` is:

`CMS_GHOST_API_URL`: http://ec2-65-0-80-107.ap-south-1.compute.amazonaws.com

**Comment by styxlab** [comment]
I am closing this issue as the originial question has been answered. Please open a new request, in case you can't solve it yourself.

**Comment by arnish12345** [comment]
Key | Value (example)
-- | --
CMS_GHOST_API_URL | https://cms.your-blog.org
CMS_GHOST_API_KEY | 9fccdb0e4ea5b572e2e5b92942

Oh I thought we have to add cms prefix like the readme, thanks for the clarification. It works now

**Comment by styxlab** [comment]
Glad you got it working! Thanks for pointing that out. Seems to be confusing, maybe I should remove the subdomain part.

**Comment by arnish12345** [comment]
Is vercel down for you ?
