### ISSUE TITLE
After deploy the ghost with vercel, how to i important content from my own installation?

### ISSUE THREAD

**Issue by francolamcn** [styxlab/next-cms-ghost#79]
I've deployed ghost with vercel, and set up the Environment Variables with url and contentAPI, but the frontend didn't make changes as i edited my post from ghost CMS, what's the next step? pls help, thanks!

**Comment by styxlab** [comment]
Hi @francolamcn! You need to create a new deploy hook on Vercel and link the hook in your Ghost Admin. This will trigger content updates whenever you update your posts in the Ghost CMS.

**Comment by francolamcn** [comment]
thanks for reply! Do i need to create a .env.lcoal file? also do i need i need to add content api key on vercel enviroment variables?

**Comment by styxlab** [comment]
You can ignore the .env.local file when deploying to Vercel. But you do need to add the Vercel environment variables as described in the README. You must do that before setting up hooks.

**Comment by francolamcn** [comment]
Thanks for your help, it works!
