### ISSUE TITLE
Setting overrideOS value to false returns build error

### ISSUE THREAD

**Issue by BeatPlus** [styxlab/next-cms-ghost#8]
Hello,

I attempted to change the overrideOS value to  False using a fresh new install and I am getting an unexpected error. 

Code changed:

```
export const overrideOS: boolean = true
```

This is my error output:

``` 

16:39:30.581 | Unhandled error during request: ReferenceError: window is not defined
-- | --
16:39:30.581 | at supportsDarkMode (/vercel/workpath0/.next/serverless/pages/404.js:3370:90)
16:39:30.581 | at getDefaultMode (/vercel/workpath0/.next/serverless/pages/404.js:3391:14)
16:39:30.581 | at getDark (/vercel/workpath0/.next/serverless/pages/404.js:3413:25)
16:39:30.581 | at DocumentHead (/vercel/workpath0/.next/serverless/pages/404.js:3499:16)


16:39:30.582 | ReferenceError: window is not defined
-- | --
16:39:30.582 | at supportsDarkMode (/vercel/workpath0/.next/serverless/pages/404.js:3370:90)
16:39:30.582 | at getDefaultMode (/vercel/workpath0/.next/serverless/pages/404.js:3391:14)
16:39:30.582 | at getDark (/vercel/workpath0/.next/serverless/pages/404.js:3413:25)
16:39:30.582 | at DocumentHead (/vercel/workpath0/.next/serverless/pages/404.js:3499:16)
16:39:30.583 | at d (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-

```

I did some investigation and I believe the usage of window function on the server side is not supposed to work, as opposed to the client. I wanted to hear your thoughts before performing more investigation.

https://github.com/styxlab/next-cms-ghost/blob/5fc7c4bee51f898bd0793fecfa6cd619c1d316f6/components/contexts/themeProvider.tsx#L19-L23

**Comment by styxlab** [comment]
Thanks for catching this bug! The window object is never present server side. A minimal correction would be something along the following line:

```
 const supportsDarkMode = () => typeof window !== 'undefined' && window.matchMedia(`(prefers-color-scheme: dark)`).matches === true 
```

This will get rid of the error, however you may also want to investigate if the OS setting is correctly picked up. It is important to clear browser cache, otherwise the previous user setting is fetched instead.
