### ISSUE TITLE
how to change stiky logo url, and fix author missing profile image?

### ISSUE THREAD

**Issue by martinscoop** [styxlab/next-cms-ghost#80]
Hello, when i scroll screen and click the logo, it will redirct to vercel generated domain name from my own domain, click sticky logo then from mydomain.com redirect to example.vercel.app, where can i edit it? 

Also, ive had image source url added in the next.config.js file, but my own prolife image won't load from vercel hosting site, it shows from my own instance ghsot cms.

**Comment by styxlab** [comment]
Welcome @martinscoop! Looks like your `SITE_URL` environment variable hasn't been set up correctly, it must be set to `mydomain.com` as described in the [README](https://github.com/styxlab/next-cms-ghost#-domain-settings).

For further questions, please show a reference to your project (url links, git repo) and config settings (you custom changes to next.config.js, appConfig.ts, etc.).

**Comment by martinscoop** [comment]
Thank you, the problems have been fixed.
