### ISSUE TITLE
MDX to posts

### ISSUE THREAD

**Issue by SebDanielsson** [styxlab/next-cms-ghost#86]
Awesome work with this theme. Pretty new på Next.js but this was fairly easy to deploy :)

Are there any plans to let you add markdown files as a source for blog posts instead of sourcing from Ghost CMS?

**Comment by styxlab** [comment]
Welcome @SebDanielsson: Great to hear you find this repo easy to deploy!

Currently there are no plans for other content sources as I am busy creating [Blogody](https://www.blogody.com/landing) a novel SaaS blogging platform. It would be fairly easy to integrate a WordPress source or MDX, so you can fork the repo and add it yourself. One thing to keep in mind with markdown is that Ghost CMS ensures a certain structure and guarantees that some key fields are always filled (e.g. the post slug). You would need to put some validation and defaults into place, so required fields are coming through properly.

**Comment by styxlab** [comment]
Closing as answered.
