### ISSUE TITLE
How to use routesConfig.ts

### ISSUE THREAD

**Issue by chancharles** [styxlab/next-cms-ghost#89]
Thanks for the great project. I am new to Next.JS but have some experience with Ghost and Gatsby. 

I was trying to figure out the purpose of the configuration file `routesConfig.ts` file. Do you mind giving me an example of how to use it?

I tried something like the following:

```
  {
    path: `technology`,
    selector: (node) => node.primary_tag && node.primary_tag.slug === `technology`,
  },
```

It doesn't create an index page under `/technology`. Instead, my posts that are tagged with `technology` appear under *both* the `/` prefix and the `/technology` prefix.

Any help is appreciated.

**Comment by styxlab** [comment]
Welcome @chancharles!

This feature is still experimental and don't seem to be working correctly (I took it over from the Gatsby variant, but didn't get around testing it).Your expectation is correct, the above config should generate a new index page under `/technology`, remove all `technology` tagged posts from the main index and show them under the new `/technology` route. The idea is described [Routing with Jamify](https://www.jamify.org/2020/04/28/routing-with-jamify/).

So, you are very welcome to use this issue as a chance to get to know NextJS better and complete this feature so it its working as expected. I don't have time to develop it myself but would review and accept a PR that does the job.

**Comment by chancharles** [comment]
Thanks for the quick response. I will take a look.

**Comment by chancharles** [comment]
I spent some time and couldn't figure out how to do it generically. Next.js's routing is mostly based on the filesystem. Although you can modify a post's URL, there seems to be no way to create an index page using dynamic routing alone. 

I can filter out unwanted posts on the homepage but the solution is incomplete without a dynamically generated index page. If you have some pointers for me to explore, I don't mind spending more time on this issue.

For my own need, I can just use filesystem-based routing.

**Comment by styxlab** [comment]
Thanks for looking into this. I think it is possible to do it generically with a [dynamic routes](https://nextjs.org/docs/routing/dynamic-routes), for example:

```
pages/[collection]/index.tsx
```

and in `index.tsx` you can get the collection var from the `context`:

```
export const getStaticProps: GetStaticProps = async (context) => {
   console.log(context.params?.collection)
}
```

Youhave to make sure that this new dynamic route does not collide with the existing ones and that a proper 404 is shown when the collection is not present. Collection paths should also be generated in getStaticPaths().

**Comment by styxlab** [comment]
@all-contributors please add @chancharles for code

**Comment by chancharles** [comment]
I have created a PR for it. [](https://github.com/styxlab/next-cms-ghost/pull/92)

I can't get it to work with your suggestion of `/pages/[collection]/index.tsx`, so I integrate the changes into existing `[...slug].tsx` It's a bit messy but it works.
