### ISSUE TITLE
Is it possible to insert Google Adsense code and make it work?

### ISSUE THREAD

**Issue by francolamcn** [styxlab/next-cms-ghost#95]
I got a problem when i insert google adsense code in <head>, `<script data-ad-client="ca-pub-1175020849521406" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>`，however, it didn't work, no ads display.

**Comment by mbernard** [comment]
Check how I did it on my repo
https://github.com/mbernard/next-cms-ghost/blob/master/components/AdWords.tsx

**Comment by francolamcn** [comment]
thanks! i've inserted it successfully!
