### ISSUE TITLE
Removing the Contact Page

### ISSUE THREAD

**Issue by chof64** [styxlab/next-cms-ghost#97]
Hello. I am trying out Ghost and Vercel with your code. And I would like to ask how to remove the contact page from the navigation bar, to easily control where I want to put it. Or alternatively, remove it and the page completely. Thank You

**Comment by styxlab** [comment]
Just set the flag in `appConfig.ts` to `false`:

```
// Contact Page
export const contactPage: boolean = false

```

**Comment by chof64** [comment]
Thank you, I didn't notice the config earlier.
