### ISSUE TITLE
Changes in post from Ghost need re deployment, why?

### ISSUE THREAD

**Issue by Huzaifaahmed20** [styxlab/next-cms-ghost#99]
After changing title in post from ghost cms, it is not reflecting changes in live site but show changes locally why it is like that, because the posts are coming from API, if I am not wrong

**Comment by styxlab** [comment]
Yes, sites on production need to be rebuild to reflect any changes in your CMS. Depending on where and how you host your `next-cms-ghost` you can set-up a webhook in the Ghost admin, connect that with your hosted site. With this set-up any new published update on your ghost CMS will trigger a re-build automatically.

In developer mode on localhost, any change in you CMS will be available instantly after a refresh.
